# minimum supported version of iOS is 10.0
platform :ios, '11.0'    

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'TestProductsAdobe' do

# Adobe ACP Pods
pod 'ACPCore', '~> 2.3.3'
pod 'ACPAnalytics', '~> 2.0'
pod 'ACPAudience', '~> 2.0'
pod 'ACPCampaign', '~> 1.0'
pod 'ACPCampaignClassic', '~> 2.0'
pod 'ACPTarget', '~> 2.0'
pod 'ACPGriffonBeta', '~> 0.0'
pod 'ACPUserProfile', '~> 2.0'

end
