# minimum supported version of iOS is 10.0
platform :ios, '11.0'    

# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'TestProductsGoogle' do

# google Firebase
pod 'Firebase/Analytics'

end